import Head from "next/head";
import AuthModal from "../auth/components/AuthModal";
import ProfileModal from "../auth/components/ProfileModal";
import Header from "../header/Header";
import Main from "../main/components/Main";
import Sidebar from "../sidebar/components/Sidebar";

type Props = {
  className?: string;
  children: React.ReactNode;
  [x: string]: any;
};

const DefaultLayout = ({ className = "", children, ...other }: Props) => {
  return (
    <>
      <Head>
        <title>Plasma IDE</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-mesh-gradient flex h-screen flex-col">
        <ProfileModal />
        <AuthModal />
        <Header />
        <div className="flex flex-1">
          <Sidebar />
          {children}
        </div>
      </div>
    </>
  );
};

export default DefaultLayout;
